### ISSUE TITLE
Feature Request: Botcommand !getclass [class_number]

### ISSUE THREAD

**Issue by dragonexpert** [JBraunsmaJr/Devry-Service-Bot#2]
This command would let you type in !getclass [CIS170] and return the name of the class.  This is helpful because you only can see channels for the classes you are currently in.  It gives you an idea of if you would be able to help a person in that class.

**Comment by tyates2020** [comment]
> 
> 
> This command would let you type in !getclass [CIS170] and return the name of the class. This is helpful because you only can see channels for the classes you are currently in. It gives you an idea of if you would be able to help a person in that class.

We would need to work on a database containing the class names, right now the only location that information is the category name. If we add a class and we don't know the propper name, we find it in the DeVry course guide.

**Comment by tyates2020** [comment]
This would take a lot of work collecting the classes, I am working on getting things grouped by major. Please wait and see results.
